/* global window */
/**
 * Belgische providers - tijdelijk apart gezet, niet gelinkt in de applicatie.
 * Om weer te activeren: content van PROVIDERS_BE toevoegen aan PROVIDERS in providers.js
 * en eventueel <script src="./providers_be.js"></script> toevoegen aan index.html met merge-logica.
 */
(() => {
  const PROVIDERS_BE = [
    {
      id: "easyvest-algemeen",
      name: "Easyvest (Algemeen beleggen Portefeuille 10)",
      website: "https://www.easyvest.be",
      type: "fondsaanbieder",
      countries: ["BE"],
      lastUpdated: "17-02-2026",
      minimumInleg: 5000,
      duurzaamheid: 'Grijs SFDR Artikel 6',
      aandelenpercentage: 100,
      fbi: false,
      tax_BE_TOB_service: "",
      tax_BE_roerende_voorheffing_service: "",
      tax_BE_effectentaks_service: "",
      tax_BE_reynderstaks_service: "",
      service_recurring_investing: true,
      service_fractional_investing: false,
      tax_BE_TOB_percentage: 0.12,
      tax_BE_TOB_max: 1300,
      overrides: { underlyingAnnualPct: 0.17 },
      underlyingCostBasis: "begin",
      fees: {
        components: [
          {
            kind: "percentOfBase",
            basis: "end",
            frequency: "monthly",
            tiers: {
              inclusiveUpper: false,
              apply: "highest",
              tiers: [
                { upTo: 25000, ratePct: 1.0 },
                { upTo: 50000, ratePct: 0.9 },
                { upTo: 100000, ratePct: 0.75 },
                { upTo: 250000, ratePct: 0.6 },
                { upTo: 1000000, ratePct: 0.5 },
                { upTo: 2500000, ratePct: 0.45 },
                { upTo: null, ratePct: 0.4 },
              ],
            },
          },
        ],
      },
      transactions: { deposit: null, withdraw: null },
    },
    {
      id: "easyvest-klimaatportefeuille",
      name: "Easyvest (Klimaatportefeuille Portefeuille 10)",
      website: "https://www.easyvest.be",
      type: "fondsaanbieder",
      countries: ["BE"],
      lastUpdated: "17-02-2026",
      minimumInleg: 5000,
      duurzaamheid: 'Lichtgroen SFDR Artikel 8',
      aandelenpercentage: 100,
      fbi: false,
      tax_BE_TOB_service: "",
      tax_BE_roerende_voorheffing_service: "",
      tax_BE_effectentaks_service: "",
      tax_BE_reynderstaks_service: "",
      service_recurring_investing: true,
      service_fractional_investing: false,
      tax_BE_TOB_percentage: 0.12,
      tax_BE_TOB_max: 1300,
      overrides: { underlyingAnnualPct: 0.20 },
      underlyingCostBasis: "begin",
      fees: {
        components: [
          {
            kind: "percentOfBase",
            basis: "end",
            frequency: "monthly",
            tiers: {
              inclusiveUpper: false,
              apply: "highest",
              tiers: [
                { upTo: 25000, ratePct: 1.0 },
                { upTo: 50000, ratePct: 0.9 },
                { upTo: 100000, ratePct: 0.75 },
                { upTo: 250000, ratePct: 0.6 },
                { upTo: 1000000, ratePct: 0.5 },
                { upTo: 2500000, ratePct: 0.45 },
                { upTo: null, ratePct: 0.4 },
              ],
            },
          },
        ],
      },
      transactions: { deposit: null, withdraw: null },
    },
    {
      id: "curvo-growth",
      name: "Curvo (Growth)",
      website: "https://curvo.eu",
      type: "fondsaanbieder",
      countries: ["BE"],
      lastUpdated: "17-02-2026",
      minimumInleg: 50,
      duurzaamheid: "Lichtgroen SFDR Artikel 8",
      aandelenpercentage: 100,
      fbi: false,
      tax_BE_TOB_service: "",
      tax_BE_roerende_voorheffing_service: "",
      tax_BE_effectentaks_service: "",
      tax_BE_reynderstaks_service: "",
      service_recurring_investing: true,
      service_fractional_investing: true,
      overrides: { underlyingAnnualPct: 0.21 },
      underlyingCostBasis: "begin",
      fees: {
        components: [
          {
            kind: "percentOfBase",
            basis: "end",
            frequency: "quarterly",
            tiers: {
              inclusiveUpper: false,
              apply: "marginal",
              tiers: [
                { upTo: 50000, ratePct: 1 },
                { upTo: 100000, ratePct: 0.85 },
                { upTo: 250000, ratePct: 0.7 },
                { upTo: null, ratePct: 0.6 },
              ],
            },
          },
        ],
      },
      transactions: { deposit: null, withdraw: null },
    },
    {
      id: "saxo-autoinvest-be",
      name: "Saxo (Autoinvest) BE",
      website: "https://www.home.saxo",
      type: "broker",
      transactionsPerMonth: 1,
      countries: ["BE"],
      lastUpdated: "18-02-2026",
      minimumInleg: null,
      duurzaamheid: null,
      aandelenpercentage: null,
      fbi: false,
      tax_BE_TOB_service: "",
      tax_BE_roerende_voorheffing_service: "",
      tax_BE_effectentaks_service: "",
      tax_BE_reynderstaks_service: "",
      service_recurring_investing: true,
      service_fractional_investing: true,
      overrides: { underlyingAnnualPct: 0.21 },
      underlyingCostBasis: "begin",
      fees: { components: [{ kind: "fixed", amount: 2 }] },
      transactions: {
        deposit: null,
        withdraw: {
          kind: "tieredTransaction",
          percentTiers: {
            tiers: [
              { upTo: 200000, ratePct: 0.08 },
              { upTo: 1000000, ratePct: 0.05 },
              { upTo: null, ratePct: 0.03 },
            ],
            inclusiveUpper: false,
            apply: "highest",
          },
          minimumAmount: 2,
        },
      },
    },
    {
      id: "rebel",
      name: "Re=Bel",
      website: "https://www.belfius.be",
      type: "broker",
      countries: ["BE"],
      lastUpdated: null,
      minimumInleg: null,
      duurzaamheid: null,
      aandelenpercentage: null,
      fbi: false,
      tax_BE_TOB_service: "",
      tax_BE_roerende_voorheffing_service: "",
      tax_BE_effectentaks_service: "",
      tax_BE_reynderstaks_service: "",
      service_recurring_investing: false,
      service_fractional_investing: false,
      tax_BE_TOB_percentage: 0.12,
      tax_BE_TOB_max: 1300,
      overrides: {},
      underlyingCostBasis: "begin",
      fees: { components: [] },
      transactions: {
        deposit: { kind: "rebelTieredFixed" },
        withdraw: { kind: "rebelTieredFixed" },
      },
    },
    {
      id: "bolero-etf-playlist",
      name: "Bolero ETF Playlist",
      website: "https://www.bolero.be",
      type: "broker",
      countries: ["BE"],
      lastUpdated: null,
      minimumInleg: null,
      duurzaamheid: null,
      aandelenpercentage: null,
      fbi: false,
      tax_BE_TOB_service: "",
      tax_BE_roerende_voorheffing_service: "",
      tax_BE_effectentaks_service: "",
      tax_BE_reynderstaks_service: "",
      service_recurring_investing: false,
      service_fractional_investing: false,
      tax_BE_TOB_percentage: 0.12,
      tax_BE_TOB_max: 1300,
      overrides: {},
      underlyingCostBasis: "begin",
      fees: { components: [] },
      transactions: {
        deposit: { kind: "boleroEtfPlaylist" },
        withdraw: { kind: "boleroEtfPlaylist" },
      },
    },
  ];

  if (typeof window !== "undefined") {
    window.PROVIDERS_BE = PROVIDERS_BE;
  }
})();
